[build]
publish = "docs/.vitepress/dist"
command = "pnpm docs:build"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/assets/*"

[headers.values]
cache-control = '''
    max-age=31536000,
    immutable'''
