packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@iconify/tools': ^4.1.2
  p-limit: ^6.2.0

catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.2
    '@antfu/ni': ^25.0.0
    bumpp: ^10.2.0
    eslint: ^9.30.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vite: ^7.0.3
  inlined:
    '@antfu/utils': ^9.2.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.0
  types:
    '@types/node': ^24.0.12
  utils:
    tinyexec: ^1.0.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
